import type { Product, Category } from '@/types';

export const sampleCategories: Category[] = [
  {
    id: '1',
    name: 'Electronics',
    slug: 'electronics',
    image_url: '',
    product_count: 24,
  },
  {
    id: '2',
    name: 'Clothing',
    slug: 'clothing',
    image_url: '',
    product_count: 56,
  },
  {
    id: '3',
    name: 'Home & Garden',
    slug: 'home-garden',
    image_url: '',
    product_count: 38,
  },
  {
    id: '4',
    name: 'Sports',
    slug: 'sports',
    image_url: '',
    product_count: 19,
  },
  {
    id: '5',
    name: 'Books',
    slug: 'books',
    image_url: '',
    product_count: 42,
  },
  {
    id: '6',
    name: 'Toys',
    slug: 'toys',
    image_url: '',
    product_count: 31,
  },
];

export const sampleProducts: Product[] = [
  {
    id: '1',
    name: 'Wireless Noise-Cancelling Headphones',
    description:
      'Premium over-ear headphones with active noise cancellation, 30-hour battery life, and crystal-clear audio quality. Perfect for music lovers and remote workers.',
    price: 299.99,
    image_url: '',
    category: 'Electronics',
    stock: 45,
    rating: 4.8,
    reviews_count: 234,
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    name: 'Organic Cotton T-Shirt',
    description:
      'Soft, breathable organic cotton t-shirt available in multiple colors. Ethically sourced and sustainably produced for the eco-conscious shopper.',
    price: 34.99,
    image_url: '',
    category: 'Clothing',
    stock: 200,
    rating: 4.5,
    reviews_count: 89,
    created_at: '2024-01-20T10:00:00Z',
  },
  {
    id: '3',
    name: 'Smart Home Security Camera',
    description:
      '1080p HD wireless security camera with night vision, two-way audio, and motion detection. Monitor your home from anywhere with the companion app.',
    price: 79.99,
    image_url: '',
    category: 'Electronics',
    stock: 120,
    rating: 4.3,
    reviews_count: 156,
    created_at: '2024-02-01T10:00:00Z',
  },
  {
    id: '4',
    name: 'Ceramic Plant Pot Set',
    description:
      'Set of 3 modern ceramic plant pots with drainage holes and bamboo saucers. Perfect for succulents, herbs, and small indoor plants.',
    price: 42.99,
    image_url: '',
    category: 'Home & Garden',
    stock: 75,
    rating: 4.7,
    reviews_count: 67,
    created_at: '2024-02-10T10:00:00Z',
  },
  {
    id: '5',
    name: 'Running Shoes - UltraBoost',
    description:
      'Lightweight and responsive running shoes with energy-returning cushioning. Designed for both casual joggers and marathon runners.',
    price: 159.99,
    image_url: '',
    category: 'Sports',
    stock: 60,
    rating: 4.6,
    reviews_count: 312,
    created_at: '2024-02-15T10:00:00Z',
  },
  {
    id: '6',
    name: 'Bestselling Novel Collection',
    description:
      'Curated collection of 5 bestselling novels from award-winning authors. Includes a mix of fiction, mystery, and literary masterpieces.',
    price: 49.99,
    image_url: '',
    category: 'Books',
    stock: 150,
    rating: 4.9,
    reviews_count: 203,
    created_at: '2024-03-01T10:00:00Z',
  },
  {
    id: '7',
    name: 'Mechanical Keyboard RGB',
    description:
      'Full-size mechanical keyboard with cherry MX switches, per-key RGB lighting, and programmable macros. Built for gamers and typists alike.',
    price: 129.99,
    image_url: '',
    category: 'Electronics',
    stock: 85,
    rating: 4.4,
    reviews_count: 178,
    created_at: '2024-03-05T10:00:00Z',
  },
  {
    id: '8',
    name: 'Yoga Mat Premium',
    description:
      'Extra-thick 6mm yoga mat with non-slip surface and alignment lines. Comes with a carrying strap. Ideal for yoga, pilates, and floor exercises.',
    price: 54.99,
    image_url: '',
    category: 'Sports',
    stock: 95,
    rating: 4.7,
    reviews_count: 145,
    created_at: '2024-03-10T10:00:00Z',
  },
  {
    id: '9',
    name: 'Denim Jacket Classic',
    description:
      'Timeless denim jacket with a modern fit. Features button closure, chest pockets, and a comfortable cotton blend fabric that gets better with wear.',
    price: 89.99,
    image_url: '',
    category: 'Clothing',
    stock: 110,
    rating: 4.5,
    reviews_count: 92,
    created_at: '2024-03-15T10:00:00Z',
  },
  {
    id: '10',
    name: 'Wooden Building Blocks Set',
    description:
      '100-piece wooden building blocks set for kids aged 3+. Non-toxic paint, smooth edges, and a variety of shapes to inspire creativity.',
    price: 29.99,
    image_url: '',
    category: 'Toys',
    stock: 180,
    rating: 4.8,
    reviews_count: 211,
    created_at: '2024-03-20T10:00:00Z',
  },
  {
    id: '11',
    name: 'Stainless Steel Water Bottle',
    description:
      'Double-walled vacuum insulated water bottle that keeps drinks cold for 24 hours or hot for 12 hours. BPA-free, leak-proof design.',
    price: 24.99,
    image_url: '',
    category: 'Sports',
    stock: 250,
    rating: 4.6,
    reviews_count: 387,
    created_at: '2024-03-25T10:00:00Z',
  },
  {
    id: '12',
    name: 'LED Desk Lamp',
    description:
      'Adjustable LED desk lamp with 5 brightness levels, 3 color temperatures, and USB charging port. Eye-friendly design reduces strain during long work sessions.',
    price: 39.99,
    image_url: '',
    category: 'Home & Garden',
    stock: 130,
    rating: 4.4,
    reviews_count: 98,
    created_at: '2024-04-01T10:00:00Z',
  },
];
